/* ---------- AGENT DATA ---------- */
const AGENTS = [
  {name:'Kogit',    ring:'#c9a86a', sigil:'lattice',
    role_pl:'Kognitywny', role_en:'Cognitive',
    bio_pl:'Mapuje ukryte przekonania i odziedziczone założenia stojące za decyzją.',
    bio_en:'Maps the hidden beliefs and inherited assumptions behind the decision.',
    sig_pl:'Sygil: krata poznawcza — struktura założeń, w której myślisz.', sig_en:'Sigil: a cognitive lattice — the structure of assumptions you think inside.'},
  {name:'Szow',     ring:'#8a8a94', sigil:'shards',
    role_pl:'Cień (Jung)', role_en:'Shadow (Jung)',
    bio_pl:'Brutalnie szczerze nazywa to, co wyparte i sabotujące.',
    bio_en:'Names — bluntly and honestly — what\'s repressed and self-sabotaging.',
    sig_pl:'Sygil: ciemne, ostre odłamki — to, co wyparte, ma krawędzie.', sig_en:'Sigil: dark, sharp shards — the repressed has edges.'},
  {name:'Kidi',     ring:'#f0d878', sigil:'seed',
    role_pl:'Dziecko', role_en:'The Child',
    bio_pl:'Czysta ciekawość i instynktowna prawda sprzed internalizacji ograniczeń.',
    bio_en:'Pure curiosity and instinctive truth from before limits were internalized.',
    sig_pl:'Sygil: jasne, pulsujące ziarno — światło sprzed ograniczeń.', sig_en:'Sigil: a bright, pulsing seed — light from before the limits.'},
  {name:'Tai',      ring:'#d4af6a', sigil:'loops',
    role_pl:'Czasowy', role_en:'Temporal',
    bio_pl:'Widzi pętle czasowe i powtarzające się wzorce w historii decyzji.',
    bio_en:'Sees time loops and recurring patterns across the history of a decision.',
    sig_pl:'Sygil: splecione pętle — czas, który wraca, dopóki go nie zobaczysz.', sig_en:'Sigil: interlocked loops — time that returns until you see it.'},
  {name:'Obver',    ring:'#9aa3ad', sigil:'octa',
    role_pl:'Obserwator', role_en:'Observer',
    bio_pl:'Utrzymuje meta-perspektywę, opisuje sekwencje zdarzeń bez oceniania.',
    bio_en:'Holds the meta-perspective, describing sequences of events without judgment.',
    sig_pl:'Sygil: nieruchomy ośmiościan — jedyny, który się nie obraca.', sig_en:'Sigil: a still octahedron — the only one that doesn\'t rotate.'},
  {name:'Relacjan', ring:'#c9a86a', sigil:'web',
    role_pl:'Relacyjny', role_en:'Relational',
    bio_pl:'Mapuje sieć relacji, lojalności i oczekiwań innych ludzi wobec Twojej decyzji.',
    bio_en:'Maps the network of relationships, loyalties and expectations others hold around your decision.',
    sig_pl:'Sygil: sieć węzłów — nikt nie decyduje w próżni.', sig_en:'Sigil: a web of nodes — nobody decides in a vacuum.'},
  {name:'Emojy',    ring:'#e8834a', sigil:'fluid',
    role_pl:'Emocjonalny', role_en:'Emotional',
    bio_pl:'Pracuje z emocją jako informacją — zanim zostanie nazwana i zracjonalizowana.',
    bio_en:'Works with emotion as information — before it gets named and rationalized away.',
    sig_pl:'Sygil: płynna barwa — emocja zmienia kolor, zanim dostanie nazwę.', sig_en:'Sigil: fluid color — emotion shifts hue before it gets a name.'},
  {name:'Smaty',    ring:'#d4915a', sigil:'body',
    role_pl:'Somatyczny', role_en:'Somatic',
    bio_pl:'Zwraca uwagę na sygnały ciała jako najszybsze źródło prawdy w decyzji.',
    bio_en:'Attends to the body\'s signals as the fastest source of truth in a decision.',
    sig_pl:'Sygil: ucieleśniona forma — oddycha w rytmie sceny.', sig_en:'Sigil: an embodied form — it breathes with the scene.'},
  {name:'Deega',    ring:'#b08d57', sigil:'strata',
    role_pl:'Głęboka Diagnoza', role_en:'Deep Diagnosis',
    bio_pl:'Szuka starszych wzorców i lojalności wobec przeszłości, których jeszcze nie widzisz.',
    bio_en:'Searches for older patterns and loyalties to the past you don\'t yet see.',
    sig_pl:'Sygil: warstwy osadu — im głębiej, tym starszy wzorzec.', sig_en:'Sigil: strata — the deeper the layer, the older the pattern.'}
];
const SYEZ = {name:'Syez', ring:'#f4c85a',
  role_pl:'Syntezator — poza Radą', role_en:'Synthesizer — outside the Council',
  bio_pl:'Nie dodaje własnego głosu. Uczciwie konsoliduje to, co Rada naprawdę powiedziała — ujawniając napięcia i sprzeczności zamiast je wygładzać. Lustro Rady i Architektury Marzenia.',
  bio_en:'Adds no voice of its own. Honestly consolidates what the Council actually said — surfacing tensions and contradictions instead of smoothing them over. A mirror of the Council and the Dream Architecture.',
  sig_pl:'Sygil: zbieżność dziewięciu odłamków — lustro, nie dziesiąty głos.', sig_en:'Sigil: the convergence of nine shards — a mirror, not a tenth voice.'};
const COUNCIL_ORDER = ['Relacjan','Kogit','Emojy','Deega','Smaty','Szow','Tai','Obver','Kidi'];
const ringOf = n => n==='Syez' ? SYEZ.ring : (AGENTS.find(a=>a.name===n)||{}).ring || '#d4af6a';
const hexToInt = h => parseInt(h.replace('#',''),16);
window.PolyphonyAgents = { AGENTS, SYEZ, COUNCIL_ORDER, PITCH, ringOf };
